doctrine:
  dbal:
    driver: 'pdo_mysql'
    user: '%env(string:DB_USER)%'
    password: '%env(string:DB_PASSWORD)%'
    host: '%env(string:DB_HOST)%'
    dbname: '%env(string:DB_NAME)%'
    port: '%env(string:DB_PORT)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '14'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Budget:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Domain/Budget/Entity'
        prefix: 'App\Domain\Budget\Entity'
        alias: Budget
      Entry:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Domain/Entry/Entity'
        prefix: 'App\Domain\Entry\Entity'
        alias: Entry
      PeriodicEntry:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Domain/PeriodicEntry/Entity'
        prefix: 'App\Domain\PeriodicEntry\Entity\PeriodicEntry'
        alias: PeriodicEntry
    dql:
      string_functions:
        ifnull: DoctrineExtensions\Query\Mysql\IfNull

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
