services:
  php:
    image: bugr2-php:latest
    build:
      context: ./docker/php
      target: dev
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_SESSION: PHPSTORM
      XDEBUG_START_WITH_REQUEST: 1
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=bugr
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/symfony/
    networks:
      - app_network

  nginx:
    image: bugr2-nginx:latest
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/symfony/
    ports:
      - "9001:80"
    networks:
      - app_network

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
      MYSQL_DATABASE: bugr
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: