shared:
  resource:
    path: ../src/Shared/Controller/
    namespace: App\Shared\Controller
  type: attribute

domain_back:
  type: attribute
  resource: '../src/Domain/**/Controller/Back/*'

domain_front:
  type: attribute
  resource: '../src/Domain/**/Controller/Front/*'
