name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    steps:
      - uses: actions/checkout@v3
      - name: Run CI
        uses: ./.github/workflows/ci.yaml

  release:
    name: Create and push docker image
    runs-on: ghcr.io/jagfx/bugr2:ci
    needs: [ ci ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install vendors
        run: composer install --no-dev --no-progress -o -n --no-scripts
      - name: Install npm
        run: npm i -p
        env:
          NODE_ENV: production
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          target: prod
          tags: ghcr.io/jagfx/bugr2:latest